import{a as L,S as w,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const v="47612462-014047a9b5080d140b4034ede",E="https://pixabay.com/api/";async function p(r,t=1,o=15){const n={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:o};try{return(await L.get(E,{params:n})).data}catch(e){throw console.error("Error fetching images:",e),e}}let m;function S({webformatURL:r,largeImageURL:t,tags:o,likes:n,views:e,comments:a,downloads:i}){return`
      <div class="image-card">
        <a href="${t}" class="image-link">
          <img src="${r}" alt="${o}" loading="lazy" class="img"/>
        </a>
        <div class="info">
          <p><b>Likes:</b> ${n}</p>
          <p><b>Views:</b> ${e}</p>
          <p><b>Comments:</b> ${a}</p>
          <p><b>Downloads:</b> ${i}</p>
        </div>
      </div>`}function b(r,t){const o=t.map(S).join("");r.insertAdjacentHTML("beforeend",o),P()}function q(r){r.innerHTML=""}function P(){m&&m.destroy(),m=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function d(r,t){r.style.display=t?"block":"none"}function c(r,t){r.style.display=t?"block":"none"}const $=document.querySelector("#search-form"),f=document.querySelector(".gallery"),g=document.querySelector(".loader"),s=document.querySelector(".load-more");let u=1,y="",h=0;$.addEventListener("submit",A);s.addEventListener("click",M);async function A(r){r.preventDefault();const t=r.target.elements.searchQuery.value.trim();if(!t){l.warning({title:"Warning",message:"Please enter a search query."});return}y=t,u=1,q(f),d(g,!0),c(s,!1);try{const o=await p(y,u);if(h=o.totalHits,o.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query."});return}b(f,o.hits),o.hits.length<h&&c(s,!0)}catch{l.error({title:"Error",message:"An error occurred while fetching images. Please try again."})}finally{d(g,!1)}}async function M(){var r;u+=1,d(g,!0),c(s,!1);try{const t=await p(y,u),o=((r=f.firstElementChild)==null?void 0:r.getBoundingClientRect().height)||0;b(f,t.hits),window.scrollBy({top:o*2,behavior:"smooth"}),u*15>=h?(c(s,!1),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):c(s,!0)}catch{l.error({title:"Error",message:"An error occurred while loading more images. Please try again."})}finally{d(g,!1)}}
//# sourceMappingURL=index.js.map
